### ISSUE TITLE
关于梯度为0的情况

### ISSUE THREAD

**Issue by wap1024** [RuoyuChen10/objectdetection-saliency-maps#11]
您好，我这边使用gardcam进行可视化时，对neck部分的网络层进行gardcam可视化，然后报错Traceback (most recent call last):
  File "d:/code/Net/demo/vis_cam.py", line 237, in <module>
    main()
  File "d:/code/Net/demo/vis_cam.py", line 214, in main
    grayscale_cam = det_cam_visualizer(
  File "d:\tcode\net\mmdet\utils\det_cam_visualizer.py", line 322, in __call__
    return self.cam(img, targets, aug_smooth, eigen_smooth)[0, :]
  File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 186, in __call__
    return self.forward(input_tensor, targets, eigen_smooth)
  File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 110, in forward
    cam_per_layer = self.compute_cam_per_layer(input_tensor, targets, eigen_smooth)
  File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 141, in compute_cam_per_layer
    cam = self.get_cam_image(input_tensor, target_layer, targets, layer_activations, layer_grads, eigen_smooth)
  File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 66, in get_cam_image
    weights = self.get_cam_weights(input_tensor, target_layer, targets, activations, grads)
  File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\grad_cam.py", line 23, in get_cam_weights
    if len(grads.shape) == 4:
AttributeError: 'NoneType' object has no attribute 'shape'   ，好像是梯度为0，请问您有遇到过这样的情况吗？

**Comment by RuoyuChen10** [comment]
> 您好，我这边使用gardcam进行可视化时，对neck部分的网络层进行gardcam可视化，然后报错Traceback (most recent call last): File "d:/code/Net/demo/vis_cam.py", line 237, in main() File "d:/code/Net/demo/vis_cam.py", line 214, in main grayscale_cam = det_cam_visualizer( File "d:\tcode\net\mmdet\utils\det_cam_visualizer.py", line 322, in **call** return self.cam(img, targets, aug_smooth, eigen_smooth)[0, :] File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 186, in **call** return self.forward(input_tensor, targets, eigen_smooth) File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 110, in forward cam_per_layer = self.compute_cam_per_layer(input_tensor, targets, eigen_smooth) File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 141, in compute_cam_per_layer cam = self.get_cam_image(input_tensor, target_layer, targets, layer_activations, layer_grads, eigen_smooth) File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\base_cam.py", line 66, in get_cam_image weights = self.get_cam_weights(input_tensor, target_layer, targets, activations, grads) File "D:\Anaconda3\envs\NET\lib\site-packages\pytorch_grad_cam\grad_cam.py", line 23, in get_cam_weights if len(grads.shape) == 4: AttributeError: 'NoneType' object has no attribute 'shape' ，好像是梯度为0，请问您有遇到过这样的情况吗？

这个有可能是MMdetection推理时候某部分存在detach()函数，使梯度截断了。另外我认为基于梯度的解释的忠实度并不高，你可以尝试使用D-RISE，你也可以关注我们最新的论文[Interpreting Object-level Foundation Models via Visual Precision Search](https://arxiv.org/abs/2411.16198)，目前我们评测针对detection或grounding任务忠实度最好的方法，我们将在论文被接收后开放代码。

**Comment by wap1024** [comment]
好的，感谢您的工作，祝您的文章早点被接收。

**Comment by wap1024** [comment]
@RuoyuChen10 您好我使用您的gradcam-retiannet.py能用来提取FCOS的热力图吗？

**Comment by RuoyuChen10** [comment]
> @RuoyuChen10 您好我使用您的gradcam-retiannet.py能用来提取FCOS的热力图吗？

我有FCOS计算saliency的代码，但是基于MMDetection 3，你需要我可以这两天传一下。

**Comment by wap1024** [comment]
我使用的是MMDetection2.4版本的，期待您的贡献，到时候看看能不能修改成mmdet 2版本的，谢谢您

**Comment by RuoyuChen10** [comment]
> 我使用的是MMDetection2.4版本的，期待您的贡献，到时候看看能不能修改成mmdet 2版本的，谢谢您

代码已更新，请见仓库，但是3.0和2.0差异蛮大的，如果你基于2.4版本我建议你看看本仓库2.x版本中yolo的代码，然后迁移到fcos。

**Comment by wap1024** [comment]
@RuoyuChen10 好的，谢谢您的工作。
